---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Нужно разработать интерфейс интернет-магазина с просмотром и фильтрацией товаров
  - Нужно разработать интерфейс интернет-магазина с добавлением их в корзину
  - Пользователь будет просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее!!!!!!!!!!
  - Пользователь будет добавлять товар в корзину и продолжать выбирать товары в каталоге!!!!!!!!!
  - На странице корзины пользователь cможет удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты!!!!!!!!!


non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Ключевой возможностью магазина будет адаптивная верстка, чтобы он был удобным на мобильных устройствах!!!!!!!!!!
  - Магазин будет SPA-приложение, которое не перезагружает страницу!!!!!!!!!
  - Корзина будет хранится в сессии браузера!!!!!!!!!!!!1
implicit:
  - Пользователь должен иметь возможность при добавлении товара в корзину указать необходимое количество непосредственно введя нужное число
  - Пользователь должен иметь возможность в корзине исправить количество товара введя нужное число
  - После оформления заказа корзина должна очищаться
  - При выборе русского языка весь текст должен стать русским за исключением названия брендов
  - При добавлении товара в корзину должно прийти подтверждение о добавлении или уведомление что товар добавлен
  - Качество изображений товаров должно быть высокого уровня
  - Пользватель должен иметь возможность просматривать дополнительные изображения в карточке товара, если такие имеются
  - При перезагрузке страницы каталог должен открываться с начальной страницы
  - При просмотре товаров должна быть возможность/кнопка вернуться назад
  - Все кнопки должны быть кликабельны
  - Название магазина вверху слева должно быть кликабельным и возвращать на начальную страницу
