---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Каталог должен просматриваться постранично
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее
  - Пользователь будет добавлять товар в корзину и продолжать выбирать товары в каталоге
  - На странице корзины пользователь cможет удалить товар из корзины и продолжить выбирать товары в каталоге
  - Можно оформить заказ с переходом на страницу оплаты

non-functional:
  - Загрузка сайта должна быть оптимизирована
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен корректно работать при большом трафике
  - Сайт должен быть доступен на различных устройствах
  - Магазин будет SPA-приложение, которое не перезагружает страницу
  - Корзина будет хранится в сессии браузера
  
implicit:
  - Пользователь должен иметь возможность при добавлении товара в корзину указать необходимое количество непосредственно введя нужное число
  - Пользователь должен иметь возможность в корзине исправить количество товара введя нужное число
  - После оформления заказа корзина должна очищаться
  - При выборе русского языка весь текст должен стать русским за исключением названий брендов
  - При добавлении товара в корзину должно прийти подтверждение о добавлении товара
  - Качество изображений товаров должно быть высокого уровня
  - Пользователь должен иметь возможность просматривать дополнительные изображения в карточке товара, если такие имеются
  - Все кнопки должны быть кликабельны
  - Название магазина вверху слева должно быть кликабельным и возвращать на начальную страницу
