---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову 
  - Пользователь должен иметь возможность искать товары по категории
  - Пользователь должен иметь возможность просматривать товары 
  - Пользователь должен иметь возможность просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Каталог должен просматриваться постранично
  - Пользователь должен иметь возможность просматривать содержимое корзины
  - Пользователь будет добавлять товар в корзину и продолжать выбирать товары в каталоге
  - На странице корзины пользователь cможет удалить товар из корзины и продолжить выбирать товары в каталоге
  - Можно оформить заказ с переходом на страницу оплаты
  - Пользователь должен иметь возможность добавить в корзину несмколько одинаковых товаров
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Магазин будет SPA-приложение, которое не перезагружает страницу
  - Корзина будет хранится в сессии браузера
  
implicit:
  - Пользователь должен иметь возможность при добавлении товара в корзину указать необходимое количество непосредственно введя нужное число
  - После оформления заказа корзина должна очищаться
  - При выборе русского языка весь текст должен стать русским за исключением названий брендов
  - При выборе английского языка весь текст должен стать английским
  - Пользователь должен иметь возможность просматривать дополнительные изображения в карточке товара, если такие имеются
  - Все ссылки должны быть кликабельны
  - Название магазина должно быть кликабельным и возвращать пользователя на начальную страницу
